### ISSUE TITLE
Populate coordinates for guides

### ISSUE THREAD

**Issue by albags** [mpi2/webapp-impc-production-tracker#442]
- [x] Add link to Sanger CRISPR finder for cas9 guides.
- [x] Move nucleases above guides in the page. 
- [x] Possible remove pams from the guide definition. 

* Need to discuss conversion of coordinates coming from the Sanger service into Build 39

Stretch goal:
- [ ] Try to set up a bowtie service to calculate coordinates for different guides. We need to test speed.

**Comment by jmason-ebi** [comment]
Not attempting the stretch goal
