### ISSUE TITLE
Usability Issue: Make it easier to update the mutation description

### ISSUE THREAD

**Issue by rwilson-ebi** [mpi2/webapp-impc-production-tracker#467]
At present it is difficult to locate the text area or text box next to the "Mutation description:" when in edit mode to add some text.

We should add some CSS to make the background highlight the text area in edit mode, or alternatively put a border around the text entry box to make it more obvious to users where to add text.

![image.png](https://images.zenhubusercontent.com/5e271a8d95a33298ccd78615/189375db-838e-4829-9786-1f5d3be7dd00)

**Comment by jmason-ebi** [comment]
Done

**Comment by jmason-ebi** [comment]
Done
